version: "3.8"

services:
  prefect-server:
    container_name: prefect-server
    image: prefecthq/prefect:3.4.4-python3.12
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      - PREFECT_UI_API_URL=http://localhost:4200/api

  prefect-worker:
    container_name: prefect-worker
    image: prefecthq/prefect:3.4.4-python3.12
    depends_on:
      - prefect-server
    working_dir: /app
    volumes:
      - ./flows:/app
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: >
      sh -c "pip install -r requirements.txt  &&
            prefect config set PREFECT_API_URL=http://prefect-server:4200/api &&
            prefect worker start --pool 'default'"